### ISSUE TITLE
Navi widget does not always consider the "overrides" option

### ISSUE THREAD

**Issue by bimlas** [denisidoro/navi#553]
**Describe the bug**

The following setting (`--preview-window=down`) is ignored if I press `C-g` in an empty prompt, only the "fallback" Navi appear as desired.

_~/.config/navi/config.yaml_

```
finder:
  command: fzf
    overrides: --no-select-1 --preview-window=down
    overrides_var: --no-select-1 --preview-window=down
```

**To Reproduce**

1. Open an empty shell
2. Press `C-g` to activate the Navi widget
3. Notice the preview window is on the top (wrong behaviour)
4. Press `Esc` and notice the preview window on the bottom (right behaviour)

Other path:

1. Open an empty shell
2. Enter text that Navi will recognize as a command that has parameter substitution
3. Press `C-g` to activate the Navi widget
4. Notice the preview window is on the down for the first time (right behaviour)

**Expected behavior**

Show the preview window on the bottom in every cases.

**Versions:**
 - OS: Ubuntu 20.04.2 LTS
 - Shell Version: zsh 5.8 (x86_64-ubuntu-linux-gnu)
 - Navi: navi 2.16.0

**Additional context**

Related issue: #546
