### ISSUE TITLE
Support add KEYBINDS to fzf command

### ISSUE THREAD

**Issue by snowman** [denisidoro/navi#718]
**Describe the solution you'd like**
Support ` --bind` switch of `fzf` to enable `Ctrl-k` to kill rest of the line

**Additional context**
```bash
# press ctrl-k to kill the rest of line after cursor
$ seq -w 5 15 | fzf --bind ctrl-k:kill-line
```

but in `navi`, none of below works:

```yaml
# FILE: config.yaml
finder:
  command: "fzf --bind ctrl-k:kill-line"
```

```bash
$ navi --finder "fzf --bind ctrl-k:kill-line"
```

```conf
# FILE: $HOME/.zshrc
alias fzf="fzf --bind ctrl-k:kill-line"
```

**Comment by lacygoill** [comment]
Pass the `--fzf-overrides-var` argument to navi:

    navi --fzf-overrides-var='--bind ctrl-k:kill-line'

Or use the `NAVI_FZF_OVERRIDES_VAR` environment variable:

    export NAVI_FZF_OVERRIDES_VAR='--bind ctrl-k:kill-line'

Or use the `FZF_DEFAULT_OPTS` environment variable:

    FZF_DEFAULT_OPTS='--bind ctrl-k:kill-line' navi

Or set the `finder.overrides_var` key in `~/.config/navi/config.yaml`:
```yaml
finder:
  command: fzf
  overrides_var: >-
    ...
    --bind ctrl-k:kill-line
    ...
```
For more info, see [Overriding fzf options](https://github.com/denisidoro/navi/blob/master/docs/customization.md#overriding-fzf-options), as well as `$ navi --help`.

**Comment by snowman** [comment]
Thank you for the details reply, it works but with one exception:

WORK
```sh
navi --fzf-overrides="--bind ctrl-k:kill-line"          # when select snippet
navi --fzf-overrides-var="--bind ctrl-k:kill-line"      # when select argument

export NAVI_FZF_OVERRIDES="--bind ctrl-k:kill-line"     # when select snippet
export NAVI_FZF_OVERRIDES_VAR="--bind ctrl-k:kill-line" # when select argument

FZF_DEFAULT_OPTS="--height 3" navi
```

```yaml
finder:
  command: fzf              # equivalent to the --finder option
  overrides: >-             # equivalent to the --fzf-overrides option
    --bind ctrl-k:kill-line
  overrides_var: >-         # equivalent to the --fzf-overrides-var option
    --bind ctrl-k:kill-line
```

NOT WORK
```sh
  FZF_DEFAULT_OPTS="--bind ctrl-k:kill-line" navi
```
