### ISSUE TITLE
Chage the app layout ? 

### ISSUE THREAD

**Issue by SamDc73** [denisidoro/navi#719]
Is there any way to remove the first column and have only two columns (one for the description and the other for the command it self) ?

**Comment by lacygoill** [comment]
Try this:

    $ cat <<'EOF' >>"$(navi info config-path)"
        style:
          tag:
            width_percentage: 15
            min_width: 15
          comment:
            width_percentage: 85
            min_width: 85
          snippet:
            width_percentage: 0
            min_width: 0
    EOF

It should set the width of the tag, comment, and snippet columns to resp. 85%, 15%, and 0%.  The snippet column will almost entirely disappear, and be reduced to 2 trailing dots.

**Comment by SamDc73** [comment]
> Try this:
> 
> ```
> $ tee --append "$(navi info config-path)" <<'EOF'
>     style:
>       tag:
>         width_percentage: 15
>       comment:
>         width_percentage: 85
>       snippet:
>         width_percentage: 0
> EOF
> ```
> 
> It should set the width of the tag, comment, and snippet columns to resp. 15%, 85%, and 0%. The snippet column will almost entirely disappear, and be reduced to 2 trailing dots.

what I'm trying to do is get rid of the tag column so tried this :
```
     style:
      tag:
        width_percentage: 0
      comment:
        width_percentage: 60
      snippet:
        width_percentage: 40
```

but the tag column is still visible
