### ISSUE TITLE
Enable the use of Bash on Windows for both Navi and fzf

### ISSUE THREAD

**Issue by giggio** [denisidoro/navi#874]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to set Bash as my shell on Windows.
I share my cheat files between OSs, and I'd like to be able to use the same cheats and not need to rewrite them.

**Describe the solution you'd like**
I'd like to be able to configure Navi so that it works with other Shells.
Like so:

````yaml
shell:
  # Shell used for shell out. Possible values: bash, zsh, dash, ...
  command: C:\Users\myuser\scoop\apps\msys2\current\usr\bin\bash.exe
  finder_command: C:\Users\myuser\scoop\apps\msys2\current\usr\bin\bash.exe
````

**Describe alternatives you've considered**
I don't know any.

**Additional context**
N/A.
